<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Library</OutputType>
		<Optimize>true</Optimize>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Company>TamKungZ_</Company>
		<Authors>TamKungZ_</Authors>
		<Product>KitsuneEngine.Security</Product>
		<Description>Simple anti-cheat service and third-party anti-cheat provider abstraction.</Description>
		<Version>1.0.0</Version>
		<AssemblyName>KitsuneEngine.Security</AssemblyName>
		<RootNamespace>KitsuneEngine.Security</RootNamespace>
	</PropertyGroup>
</Project>
